var searchData=
[
  ['hashalgorithmnames',['HashAlgorithmNames',['../class_windows_1_1_security_1_1_cryptography_1_1_core_1_1_hash_algorithm_names.html',1,'Windows::Security::Cryptography::Core']]],
  ['hashalgorithmprovider',['HashAlgorithmProvider',['../class_windows_1_1_security_1_1_cryptography_1_1_core_1_1_hash_algorithm_provider.html',1,'Windows::Security::Cryptography::Core']]],
  ['hasvariantattribute',['HasVariantAttribute',['../class_windows_1_1_foundation_1_1_metadata_1_1_has_variant_attribute.html',1,'Windows::Foundation::Metadata']]],
  ['highlightsandshadowseffect',['HighlightsAndShadowsEffect',['../class_microsoft_1_1_graphics_1_1_canvas_1_1_effects_1_1_highlights_and_shadows_effect.html',1,'Microsoft::Graphics::Canvas::Effects']]],
  ['holdingroutedeventargs',['HoldingRoutedEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_input_1_1_holding_routed_event_args.html',1,'Windows::UI::Xaml::Input']]],
  ['hstring_5f_5fsystem_5fprivate_5finterop',['HSTRING__System_Private_Interop',['../struct_system_1_1_runtime_1_1_interop_services_1_1_h_s_t_r_i_n_g_____system___private___interop.html',1,'System::Runtime::InteropServices']]],
  ['httpbaseprotocolfilter',['HttpBaseProtocolFilter',['../class_windows_1_1_web_1_1_http_1_1_filters_1_1_http_base_protocol_filter.html',1,'Windows::Web::Http::Filters']]],
  ['httpcachecontrol',['HttpCacheControl',['../class_windows_1_1_web_1_1_http_1_1_filters_1_1_http_cache_control.html',1,'Windows::Web::Http::Filters']]],
  ['httpclient',['HttpClient',['../class_windows_1_1_web_1_1_http_1_1_http_client.html',1,'Windows::Web::Http']]],
  ['httpcontentheadercollection',['HttpContentHeaderCollection',['../class_windows_1_1_web_1_1_http_1_1_headers_1_1_http_content_header_collection.html',1,'Windows::Web::Http::Headers']]],
  ['httpmediatypeheadervalue',['HttpMediaTypeHeaderValue',['../class_windows_1_1_web_1_1_http_1_1_headers_1_1_http_media_type_header_value.html',1,'Windows::Web::Http::Headers']]],
  ['httpmethod',['HttpMethod',['../class_windows_1_1_web_1_1_http_1_1_http_method.html',1,'Windows::Web::Http']]],
  ['httpprogress',['HttpProgress',['../struct_windows_1_1_web_1_1_http_1_1_http_progress.html',1,'Windows::Web::Http']]],
  ['httprequestheadercollection',['HttpRequestHeaderCollection',['../class_windows_1_1_web_1_1_http_1_1_headers_1_1_http_request_header_collection.html',1,'Windows::Web::Http::Headers']]],
  ['httprequestmessage',['HttpRequestMessage',['../class_windows_1_1_web_1_1_http_1_1_http_request_message.html',1,'Windows::Web::Http']]],
  ['httpresponseheadercollection',['HttpResponseHeaderCollection',['../class_windows_1_1_web_1_1_http_1_1_headers_1_1_http_response_header_collection.html',1,'Windows::Web::Http::Headers']]],
  ['httpresponsemessage',['HttpResponseMessage',['../class_windows_1_1_web_1_1_http_1_1_http_response_message.html',1,'Windows::Web::Http']]],
  ['huerotationeffect',['HueRotationEffect',['../class_microsoft_1_1_graphics_1_1_canvas_1_1_effects_1_1_hue_rotation_effect.html',1,'Microsoft::Graphics::Canvas::Effects']]],
  ['huetorgbeffect',['HueToRgbEffect',['../class_microsoft_1_1_graphics_1_1_canvas_1_1_effects_1_1_hue_to_rgb_effect.html',1,'Microsoft::Graphics::Canvas::Effects']]],
  ['hyperlink',['Hyperlink',['../class_windows_1_1_u_i_1_1_xaml_1_1_documents_1_1_hyperlink.html',1,'Windows::UI::Xaml::Documents']]],
  ['hyperlinkclickeventargs',['HyperlinkClickEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_documents_1_1_hyperlink_click_event_args.html',1,'Windows::UI::Xaml::Documents']]]
];
