var searchData=
[
  ['fileactivatedeventargs',['FileActivatedEventArgs',['../class_windows_1_1_application_model_1_1_activation_1_1_file_activated_event_args.html',1,'Windows::ApplicationModel::Activation']]],
  ['fileio',['FileIO',['../class_windows_1_1_storage_1_1_file_i_o.html',1,'Windows::Storage']]],
  ['fileopenpickeractivatedeventargs',['FileOpenPickerActivatedEventArgs',['../class_windows_1_1_application_model_1_1_activation_1_1_file_open_picker_activated_event_args.html',1,'Windows::ApplicationModel::Activation']]],
  ['filesavepickeractivatedeventargs',['FileSavePickerActivatedEventArgs',['../class_windows_1_1_application_model_1_1_activation_1_1_file_save_picker_activated_event_args.html',1,'Windows::ApplicationModel::Activation']]],
  ['flyoutbase',['FlyoutBase',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_primitives_1_1_flyout_base.html',1,'Windows::UI::Xaml::Controls::Primitives']]],
  ['flyoutbaseclosingeventargs',['FlyoutBaseClosingEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_primitives_1_1_flyout_base_closing_event_args.html',1,'Windows::UI::Xaml::Controls::Primitives']]],
  ['flyoutpresenter',['FlyoutPresenter',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_flyout_presenter.html',1,'Windows::UI::Xaml::Controls']]],
  ['focusdisengagedeventargs',['FocusDisengagedEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_focus_disengaged_event_args.html',1,'Windows::UI::Xaml::Controls']]],
  ['focusengagedeventargs',['FocusEngagedEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_focus_engaged_event_args.html',1,'Windows::UI::Xaml::Controls']]],
  ['focusmanager',['FocusManager',['../class_windows_1_1_u_i_1_1_xaml_1_1_input_1_1_focus_manager.html',1,'Windows::UI::Xaml::Input']]],
  ['fontfamily',['FontFamily',['../class_windows_1_1_u_i_1_1_xaml_1_1_media_1_1_font_family.html',1,'Windows::UI::Xaml::Media']]],
  ['fonticon',['FontIcon',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_font_icon.html',1,'Windows::UI::Xaml::Controls']]],
  ['fontweight',['FontWeight',['../struct_windows_1_1_u_i_1_1_text_1_1_font_weight.html',1,'Windows::UI::Text']]],
  ['foundationcontract',['FoundationContract',['../struct_windows_1_1_foundation_1_1_foundation_contract.html',1,'Windows::Foundation']]],
  ['frame',['Frame',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_frame.html',1,'Windows::UI::Xaml::Controls']]],
  ['frameworkelement',['FrameworkElement',['../class_windows_1_1_u_i_1_1_xaml_1_1_framework_element.html',1,'Windows::UI::Xaml']]],
  ['frameworktemplate',['FrameworkTemplate',['../class_windows_1_1_u_i_1_1_xaml_1_1_framework_template.html',1,'Windows::UI::Xaml']]]
];
