var searchData=
[
  ['mainpage',['MainPage',['../class_i_v_s_calc_1_1_main_page.html',1,'IVSCalc']]],
  ['manipulationcompletedroutedeventargs',['ManipulationCompletedRoutedEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_input_1_1_manipulation_completed_routed_event_args.html',1,'Windows::UI::Xaml::Input']]],
  ['manipulationdelta',['ManipulationDelta',['../struct_windows_1_1_u_i_1_1_input_1_1_manipulation_delta.html',1,'Windows::UI::Input']]],
  ['manipulationdeltaroutedeventargs',['ManipulationDeltaRoutedEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_input_1_1_manipulation_delta_routed_event_args.html',1,'Windows::UI::Xaml::Input']]],
  ['manipulationinertiastartingroutedeventargs',['ManipulationInertiaStartingRoutedEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_input_1_1_manipulation_inertia_starting_routed_event_args.html',1,'Windows::UI::Xaml::Input']]],
  ['manipulationstartedroutedeventargs',['ManipulationStartedRoutedEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_input_1_1_manipulation_started_routed_event_args.html',1,'Windows::UI::Xaml::Input']]],
  ['manipulationstartingroutedeventargs',['ManipulationStartingRoutedEventArgs',['../class_windows_1_1_u_i_1_1_xaml_1_1_input_1_1_manipulation_starting_routed_event_args.html',1,'Windows::UI::Xaml::Input']]],
  ['marshalingbehaviorattribute',['MarshalingBehaviorAttribute',['../class_windows_1_1_foundation_1_1_metadata_1_1_marshaling_behavior_attribute.html',1,'Windows::Foundation::Metadata']]],
  ['math',['Math',['../class_i_v_s_calc_1_1_math.html',1,'IVSCalc']]],
  ['mathclasstest',['MathClassTest',['../class_tests_1_1_math_class_test.html',1,'Tests']]],
  ['matrix5x4',['Matrix5x4',['../struct_microsoft_1_1_graphics_1_1_canvas_1_1_effects_1_1_matrix5x4.html',1,'Microsoft::Graphics::Canvas::Effects']]],
  ['mediacapture',['MediaCapture',['../class_windows_1_1_media_1_1_capture_1_1_media_capture.html',1,'Windows::Media::Capture']]],
  ['mediacaptureinitializationsettings',['MediaCaptureInitializationSettings',['../class_windows_1_1_media_1_1_capture_1_1_media_capture_initialization_settings.html',1,'Windows::Media::Capture']]],
  ['mediaelement',['MediaElement',['../class_windows_1_1_u_i_1_1_xaml_1_1_controls_1_1_media_element.html',1,'Windows::UI::Xaml::Controls']]],
  ['memorymanager',['MemoryManager',['../class_windows_1_1_system_1_1_memory_manager.html',1,'Windows::System']]],
  ['messagedialog',['MessageDialog',['../class_windows_1_1_u_i_1_1_popups_1_1_message_dialog.html',1,'Windows::UI::Popups']]],
  ['morphologyeffect',['MorphologyEffect',['../class_microsoft_1_1_graphics_1_1_canvas_1_1_effects_1_1_morphology_effect.html',1,'Microsoft::Graphics::Canvas::Effects']]],
  ['museattribute',['MuseAttribute',['../class_windows_1_1_foundation_1_1_metadata_1_1_muse_attribute.html',1,'Windows::Foundation::Metadata']]]
];
